### ISSUE TITLE
Is this an ai

### ISSUE THREAD

**Issue by CipherVector** [Yoyolick/ClashRoyaleAI#3]
I was wondering if this is just an algorithm or actual artificial intelligence from what I see it doesn't use any models or have any function to train, additionally is the project still in active development.

**Comment by zoogies** [comment]
It's just an algorithm, I played around with using ML during part of the process of making it but decided against it since someone else had tried that approach and it was way more work than it was worth.

And no, this is not in active development it was more of a side project for a few days.

Let me know if you had any other questions :)
